version: '3'
services:
    php-fpm:
        container_name: todolist_php-fpm
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - '.:/var/www/todolist:rw,delegated'
            - './docker/php/conf/php.ini:/usr/local/etc/php/php.ini'
        restart: always
    web:
        container_name: todolist_nginx
        image: nginx:latest
        ports:
            - "8888:80"
        links:
            - php-fpm
        volumes:
            - './:/var/www/todolist:rw'
            - './docker/nginx/conf/core/nginx.conf:/etc/nginx/nginx.conf'
            - './docker/nginx/conf/development/todolist.conf:/etc/nginx/conf.d/default.conf'
        restart: always
    mysql:
        container_name: todolist_mysql
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'coucou'
            MYSQL_DATABASE: 'db123'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
        restart: always
volumes:
    mysqldata: {}